### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by Karmov69** [nuxt-community/svg-sprite-module#119]
Tell me please,  how to change color svg?

**Comment by AndrewBogdanovTSS** [comment]
@Karmov69 do you want to change overall color of the icon or some of it's internal parts?
In case it's whole color - you can set fill property of all paths inside of your icon to **currentColor** and than specify color by applying some outer css, for example:

some-icon.svg:
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path fill="currentColor" d="M3 8.4l9 9 7-7V15h2V7h-8v2h4.6L12 14.6 4.4 7 3 8.4z"/></svg>
```

outer css:
```
.svg-icon {
    color: green;
}
```
you can also just set color prop on the svg-icon component since all the properties automatically propagate to the underlying svg tag - it will also change the color of your icon if internal path was previously set to **currentColor**

**Comment by MoonCheung** [comment]
@AndrewBogdanovTSS It doesn't work to try as you say, or it's still the same color, you can't change the color of the SVG icon

**Comment by farnabaz** [comment]
@Karmov69 @MoonCheung Changing icons color is very dependant on SVG structure, sometimes you need to make a little change in the original icon in order to it works. Place one of your icons here so we could find out together

**Comment by AndrewBogdanovTSS** [comment]
@MoonCheung it's working 100% - I used this approach for quite a long time now. As @farnabaz it's your SVG or you did something not the way I wrote. Please, create a repro for us to look at

**Comment by MoonCheung** [comment]
```javascript
<svg t="1575609862952" class="icon" viewBox="0 0 1447 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ...... p-id="7203" fill="currentColor"></path></svg>`
```
Individual component local styles in the pages file:
```scss
.icon {
 color: blue;
}
```
`.icon` This is `elementClass: 'icon'`. I didn't think I could change the color of the SVG icon, but now I can change the color of the SVG icon

**Comment by AndrewBogdanovTSS** [comment]
@MoonCheung you're welcome.
@farnabaz I guess this issue can be closed
