### ISSUE TITLE
symbols tags are being rendered outside defs tags

### ISSUE THREAD

**Issue by pisandelli** [nuxt-community/svg-sprite-module#181]
Hi all, thanks for the amazing plugin.
I just realised that the `<symbol>` is being rendered outside the `<defs>`. I'm not shure it's a bug or an expected behavior, but AFAIK they should be inside the `<defs>`.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>

</defs>
<symbol id="i-activity">
  <path d="M11.961 3.336a.668.668 0 00-.592.448l-.001.005-3.849 11.544H2.667a.667.667 0 100 1.334H8a.667.667 0 00.631-.451l.001-.005 3.367-10.102 7.367 22.101a.668.668 0 001.264.005l.001-.005 3.849-11.544h4.852a.667.667 0 100-1.334h-5.333a.667.667 0 00-.631.451l-.001.005L20 25.89 12.633 3.789a.668.668 0 00-.632-.454l-.042.001h.002z"/>
</symbol>  
</svg>
```
Version: 0.4.11

**Comment by farnabaz** [comment]
Hey,
This is expected behavior indeed. These symbols are the main part of an svg-sprite. Take a look at ara Soueidan's great article about SVG-Sprites. [An Overview of SVG Sprite Creation Techniques](https://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/).  

Also, there is a reason for this `<defs>` tag. Some symbols have their own `defs` and browsers do not support `<defs>` inside the `<symbol>`. module extracts symbols defs and put them together in this specific tag.

I close this issue but feel free to ask anything or reopen the issue 🙂
